// flow-typed signature: 6ebdc013bc5dcba086dd0aa41286cbc6
// flow-typed version: <<STUB>>/react-native-navigation_v^1.1.81/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-navigation/docs/sw' {
  declare module.exports: any;
}

declare module 'react-native-navigation/scripts/release' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/controllers/Constants' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/controllers/index' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/controllers/utils' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/indexDeprecated.android' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/indexDeprecated.ios' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/platformSpecificDeprecated.android' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/deprecated/platformSpecificDeprecated.ios' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/index' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/Navigation' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/platformSpecific.android' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/platformSpecific.ios' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/PropRegistry' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/Screen' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/views/sharedElementTransition.android' {
  declare module.exports: any;
}

declare module 'react-native-navigation/src/views/sharedElementTransition.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-navigation/docs/sw.js' {
  declare module.exports: $Exports<'react-native-navigation/docs/sw'>;
}
declare module 'react-native-navigation/scripts/release.js' {
  declare module.exports: $Exports<'react-native-navigation/scripts/release'>;
}
declare module 'react-native-navigation/src/deprecated/controllers/Constants.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/controllers/Constants'>;
}
declare module 'react-native-navigation/src/deprecated/controllers/index.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/controllers/index'>;
}
declare module 'react-native-navigation/src/deprecated/controllers/utils.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/controllers/utils'>;
}
declare module 'react-native-navigation/src/deprecated/indexDeprecated.android.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/indexDeprecated.android'>;
}
declare module 'react-native-navigation/src/deprecated/indexDeprecated.ios.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/indexDeprecated.ios'>;
}
declare module 'react-native-navigation/src/deprecated/platformSpecificDeprecated.android.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/platformSpecificDeprecated.android'>;
}
declare module 'react-native-navigation/src/deprecated/platformSpecificDeprecated.ios.js' {
  declare module.exports: $Exports<'react-native-navigation/src/deprecated/platformSpecificDeprecated.ios'>;
}
declare module 'react-native-navigation/src/index.js' {
  declare module.exports: $Exports<'react-native-navigation/src/index'>;
}
declare module 'react-native-navigation/src/Navigation.js' {
  declare module.exports: $Exports<'react-native-navigation/src/Navigation'>;
}
declare module 'react-native-navigation/src/platformSpecific.android.js' {
  declare module.exports: $Exports<'react-native-navigation/src/platformSpecific.android'>;
}
declare module 'react-native-navigation/src/platformSpecific.ios.js' {
  declare module.exports: $Exports<'react-native-navigation/src/platformSpecific.ios'>;
}
declare module 'react-native-navigation/src/PropRegistry.js' {
  declare module.exports: $Exports<'react-native-navigation/src/PropRegistry'>;
}
declare module 'react-native-navigation/src/Screen.js' {
  declare module.exports: $Exports<'react-native-navigation/src/Screen'>;
}
declare module 'react-native-navigation/src/views/sharedElementTransition.android.js' {
  declare module.exports: $Exports<'react-native-navigation/src/views/sharedElementTransition.android'>;
}
declare module 'react-native-navigation/src/views/sharedElementTransition.ios.js' {
  declare module.exports: $Exports<'react-native-navigation/src/views/sharedElementTransition.ios'>;
}
